<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.75.0.4207" />
    <PackageReference Include="KickLib" Version="1.13.1" />
    <PackageReference Include="SocketIOClient" Version="4.0.5" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.10" />
    <PackageReference Include="TwitchLib.Api" Version="3.10.2" />
    <PackageReference Include="TwitchLib.EventSub.Websockets" Version="0.8.0" />
  </ItemGroup>

</Project>
